low_level_motor_controller_left:
  ros__parameters:
    motor_id: "left"
    controller_rate: 1000
    current_max: 3.0
    speed_min: 900.0
    speed_max: 23000.0
    acc_max: 5000.0
    pid:
      kp: 0.0008 # 0.004
      ki: 0.0001 # 0.004
      kd: 0.0 # 0.0001
    robot:
      wheel_diameter: 0.15
      wheel_base: 0.224
      motor_pulley_teeth: 15
      wheel_pulley_teeth: 60
      gear_ratio: 0.25
      motor_pole_pairs: 7
low_level_motor_controller_right:
  ros__parameters:
    motor_id: "right"
    controller_rate: 1000
    current_max: 3.0
    speed_min: 900.0
    speed_max: 23000.0
    acc_max: 5000.0
    pid:
      kp: 0.0008 # 0.004
      ki: 0.0001 # 0.004
      kd: 0.0 # 0.0001
    robot:
      wheel_diameter: 0.15
      wheel_base: 0.224
      motor_pulley_teeth: 15
      wheel_pulley_teeth: 60
      gear_ratio: 0.25
      motor_pole_pairs: 7
twist_to_diff_drive:
  ros__parameters:
    controller_rate: 1000.0
    target_velocity: 5.0
pos_controller:
  ros__parameters:
    controller_rate: 1000.0
    target_velocity: 1.0
    pos_tolerance: 0.05
    pid_linear:
      kp: 1.0
      ki: 0.0
      kd: 0.0
    pid_angular:
      kp: 1.0
      ki: 0.0
      kd: 0.0
